"""English-first terminal text; Chinese when the locale starts with zh."""
import os


def is_zh():
    for name in ('LC_ALL', 'LC_MESSAGES', 'LANG'):
        value = os.environ.get(name)
        if value:
            return value.lower().startswith('zh')
    return False


STRINGS = {
    'en': {
        'title': 'AZIR DISPATCH · Roles & models',
        'detected': 'detected',
        'loading': 'Reading model lists from the installed CLIs ...',
        'none': 'none',
        'role': 'ROLE', 'executor': 'EXECUTOR', 'model': 'MODEL', 'effort': 'EFFORT', 'status': 'STATUS',
        'role.main': 'main', 'role.dev': 'dev', 'role.review': 'review',
        'role.research': 'research', 'role.advisor': 'advisor',
        'role.main.desc': 'main: the session you talk to. It plans, dispatches and reviews.',
        'role.dev.desc': 'dev: writes code for dispatched tasks.',
        'role.review.desc': 'review: reads finished work and reports problems.',
        'role.research.desc': 'research: looks things up and writes findings.',
        'role.advisor.desc': 'advisor: a second opinion on hard calls. Optional.',
        'falls_back': 'Falls back to {fallback} if {executor} is missing.',
        'no_fallback': 'No fallback is configured.',
        'not_configured': 'not configured',
        's.verified': '✓ verified', 's.connected': '✓ connected', 's.unverified': '· not tested', 's.optional': 'optional',
        's.failed': '✗ test failed', 's.failed.model_not_found': '✗ model not found',
        's.failed.not_logged_in': '✗ not logged in', 's.failed.command_missing': '✗ command not found',
        's.failed.timeout': '✗ no reply', 's.not_in_list': '✗ not in {executor} model list',
        's.fallback': '→ {fallback}', 's.missing': '✗ nothing installed',
        'keys': '↑↓ select  ←→ executor  m model  e effort  t test  s save  q quit',
        'saved': 'Saved {path}',
        'unsaved': '(unsaved changes)',
        'too_small': 'Terminal too small: need at least {cols}x{rows}, have {have_cols}x{have_rows}. Enlarge the window or run `azir-dispatch roles --json`.',
        'confirm_test': 'Test {combo}? One short message, uses a little quota. y/n',
        'testing': 'Testing {combo} ...',
        'test_ok': '✓ {combo} replied ({seconds:.1f}s)',
        'test_fail': '✗ {combo}: {reason}',
        'r.command_missing': 'command not found: {command}',
        'r.not_logged_in': 'not logged in. Log in with `{command}` and retry.',
        'r.model_not_found': 'model not found for this account: {model}',
        'r.timeout': 'no reply within {seconds}s',
        'r.unexpected': 'unexpected reply: {detail}',
        'r.error': 'failed: {detail}',
        'pick_model': 'Model for {role} ({executor}). ↑↓ choose  Enter select  Esc cancel',
        'type_model': 'type a model name…', 'inherit_label': 'inherit (the CLI\'s own default)',
        'manual_prompt': 'Model name (Enter to accept, Esc to cancel): ',
        'cannot_edit': 'Nothing to change here.',
        'cannot_test': 'This executor is a signed-in browser, not a CLI. `azir-dispatch advisor` tests it.',
        'no_executor': 'No other executor is installed.',
        'setset_ok': '{role}: {before} → {after}',
        'setset_same': '{role}: unchanged ({after})',
        'setset_error': 'error: {message}',
        'saved_to': 'saved to {path}',
        # doctor
        'doctor.optional': 'optional', 'doctor.not_set': 'not set', 'doctor.set': 'set',
        'doctor.not_installed': 'not installed', 'doctor.version_unknown': 'version unknown',
        'doctor.need_agent': 'need at least one agent CLI ({names})',
        'doctor.no_role': 'no executor available', 'doctor.jev_rules': 'rules mode',
        'doctor.jev_online': 'JEV mode (online ability untested)',
        'doctor.next': 'Next: run `azir-dispatch roles` to review and change roles and models.',
        'doctor.failed': 'Check failed: look at the config format and the state directory permissions.',
        # setup summary
        'setup.title': 'Setup plan', 'setup.applied': 'Setup applied',
        'setup.file': 'Config file', 'setup.unchanged': 'no changes needed',
        'setup.will_write': 'will write', 'setup.wrote': 'wrote',
        'setup.roles': 'Roles', 'setup.next': 'Next',
        'setup.next_apply': 'Save it: rerun the same command with --apply',
        'setup.next_roles': 'Review roles and models: azir-dispatch roles',
        'setup.next_demo': 'Open the dispatch board: azir-dispatch demo',
        'setup.json_hint': 'Machine-readable output: add --json',
        'setup.failed': 'Setup failed',
        'setup.mode': 'JEV mode',
        'setup.privacy': 'Privacy rules',
        'setup.hooks': 'Hooks',
        'setup.hooks_none': 'none planned',
        'setup.status.needs_confirmation': 'Not saved yet.',
    },
    'zh': {
        'title': 'AZIR DISPATCH · 角色与模型',
        'detected': '已检测到',
        'loading': '正在读取已安装 CLI 的型号列表 ……',
        'none': '无',
        'role': '角色', 'executor': '执行者', 'model': '型号', 'effort': '强度', 'status': '状态',
        'role.main': '主会话', 'role.dev': '开发', 'role.review': '审查',
        'role.research': '调研', 'role.advisor': '顾问',
        'role.main.desc': '主会话：和你对话的那一个，负责规划、派发和验收。',
        'role.dev.desc': '开发：为派发的任务写代码。',
        'role.review.desc': '审查：检查做完的工作并报告问题。',
        'role.research.desc': '调研：查资料并写出结论。',
        'role.advisor.desc': '顾问：重大取舍时给第二意见，可选。',
        'falls_back': '{executor} 没装时，退到 {fallback}。',
        'no_fallback': '没有配置备选。',
        'not_configured': '未配置',
        's.verified': '✓ 已验证', 's.connected': '✓ 已连接', 's.unverified': '· 未测试', 's.optional': '可选',
        's.failed': '✗ 测试失败', 's.failed.model_not_found': '✗ 没有这个型号',
        's.failed.not_logged_in': '✗ 没登录', 's.failed.command_missing': '✗ 找不到命令',
        's.failed.timeout': '✗ 没有回复', 's.not_in_list': '✗ 不在 {executor} 型号列表里',
        's.fallback': '→ 退到 {fallback}', 's.missing': '✗ 一个都没装',
        'keys': '↑↓ 选角色  ←→ 换执行者  m 型号  e 强度  t 测试  s 保存  q 退出',
        'saved': '已保存 {path}',
        'unsaved': '（有未保存的修改）',
        'too_small': '终端太小：至少需要 {cols}x{rows}，现在是 {have_cols}x{have_rows}。请放大窗口，或运行 `azir-dispatch roles --json`。',
        'confirm_test': '测试 {combo}？发一句话，会消耗一点额度。y/n',
        'testing': '正在测试 {combo} ……',
        'test_ok': '✓ {combo} 已回复（{seconds:.1f} 秒）',
        'test_fail': '✗ {combo}：{reason}',
        'r.command_missing': '找不到命令：{command}',
        'r.not_logged_in': '没有登录。先运行 `{command}` 登录，再重试。',
        'r.model_not_found': '这个账号下没有这个型号：{model}',
        'r.timeout': '{seconds} 秒内没有回复',
        'r.unexpected': '回复不符合预期：{detail}',
        'r.error': '失败：{detail}',
        'pick_model': '为 {role}（{executor}）选型号。↑↓ 选择  回车确定  Esc 取消',
        'type_model': '手动输入型号……', 'inherit_label': 'inherit（用该 CLI 自己的默认）',
        'manual_prompt': '型号名（回车确定，Esc 取消）：',
        'cannot_edit': '这里没有可改的。',
        'cannot_test': '这个执行者是已登录的浏览器，不是 CLI。用 `azir-dispatch advisor` 测试。',
        'no_executor': '没有安装其他执行者。',
        'setset_ok': '{role}：{before} → {after}',
        'setset_same': '{role}：没有变化（{after}）',
        'setset_error': '错误：{message}',
        'saved_to': '已保存到 {path}',
        'doctor.optional': '可选', 'doctor.not_set': '未设置', 'doctor.set': '已设置',
        'doctor.not_installed': '未安装', 'doctor.version_unknown': '版本未识别',
        'doctor.need_agent': '至少需要装一个 agent CLI（{names}）',
        'doctor.no_role': '暂无可用执行者', 'doctor.jev_rules': '规则模式',
        'doctor.jev_online': 'JEV 模式（在线能力未验证）',
        'doctor.next': '下一步：运行 `azir-dispatch roles`，查看并修改角色和型号。',
        'doctor.failed': '检测失败：请检查配置格式和状态目录权限。',
        'setup.title': '安装计划', 'setup.applied': '安装完成',
        'setup.file': '配置文件', 'setup.unchanged': '无需改动',
        'setup.will_write': '将写入', 'setup.wrote': '已写入',
        'setup.roles': '角色', 'setup.next': '下一步',
        'setup.next_apply': '保存：用同样的命令加 --apply 再运行一次',
        'setup.next_roles': '查看并修改角色和型号：azir-dispatch roles',
        'setup.next_demo': '打开调度图：azir-dispatch demo',
        'setup.json_hint': '需要机器可读输出：加 --json',
        'setup.failed': '安装失败',
        'setup.mode': 'JEV 模式',
        'setup.privacy': '隐私规则',
        'setup.hooks': 'Hooks',
        'setup.hooks_none': '没有计划',
        'setup.status.needs_confirmation': '还没有保存。',
    },
}


def tr(key, **values):
    table = STRINGS['zh' if is_zh() else 'en']
    text = table.get(key) or STRINGS['en'].get(key, key)
    return text.format(**values) if values else text
